title = "AI LAB"
baseURL = ""
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
tags = ["AI", "Data Science", "ML", "LLM", "SLM"]
languageCode = "en-us"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = "tomanistor"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
  author = "AI Lab"
  description = "Working towards AI for all languages"
  logoBig = "/images/ailab-logo-wo-text.png"
  logoSmall = "/images/ailab-logo-wo-text-sm.png"
  favicon = "favicon.ico"
  opengraphImage = "/images/osprey.png"
  email = ""
  googleTagManager = ""
  customCSS = true

  # Social media links in footer
  twitter = ""
  linkedin = "tbilisi-ai-lab"
  github = "Tbilisi-AI-Lab"
  huggingface = "tbilisi-ai-lab"
  facebook = "ailab.ge"

  # Copyright and theme author credit in footer
  copyright = true
  credit = false

  # Cache busting of static resources (additional set up required)
  cacheBustCSS = true
  cacheBustJS = true

  # Code highlighting with highlight.js
  highlightJS = true
  highlightJSStyle = "" # For custom highlight.js styles, add your /path/to/styles/default.css
  highlightJSScript = "" # For custom highlight.js languages config, add your /path/to/highlight.pack.js

  # Choose either Formspree contact form or Basin contact form
  ajaxFormspree = false
  ajaxFormspreeGold = false
  ajaxBasin = "https://usebasin.com/f/0eae7044d4c2"

  # Lazy loading with lazysizes
  lazyloading = true


[languages]
  [languages.en]
    title = "AI LAB"
    tagline = "Tbilisi AI Lab"
    languageName = "English"
    weight = 1
      [[languages.en.menu.main]]
        name = "About"
        url = "/#about"
        weight = 2
      [[languages.en.menu.main]]
        name = "Blog"
        url  = "/#blog"
        weight = 3
      [[languages.en.menu.main]]
        name = "Contact"
        url  = "/#contact"
        weight = 4
  [languages.ka]
    title = "აი ლაბი"
    tagline = "აი ლაბი"
    languageName = "Georgian"
    weight = 5
      [[languages.ka.menu.main]]
          name = "ჩვენ"
          url = "/#about"
          weight = 6
      [[languages.ka.menu.main]]
          name = "ამბები"
          url  = "/#blog"
          weight = 7
      [[languages.ka.menu.main]]
          name = "კავშირი"
          url  = "/#contact"
          weight = 8