name = "Osprey"
license = "Apache License 2.0"
licenselink = "https://github.com/tomanistor/osprey/blob/master/LICENSE.md"
description = "Clean, responsive one-page portfolio accompanied by a minimalist blog."
homepage = "https://github.com/tomanistor/osprey"
tags = ["blog", "portfolio", "gallery", "minimalist", "responsive", "flexbox"]
features = ["blog", "portfolio", "google analytics"]
min_version = "0.5"

[author]
  name = "Toma Nistor"
  homepage = "https://tomanistor.com"


title = "Osprey Example Site"
baseURL = "https://tomanistor.com"
tags = ["portfolio", "web design", "blog"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = "tomanistor"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
  tagline = "Osprey Example Site"
  author = "Toma Nistor"
  description = "Full-stack web developer and UI/UX enthusiast based in San Diego, CA."
  logoBig = "/images/osprey-logo.png"
  logoSmall = "/images/osprey-logo.png"
  favicon = "favicon.ico"
  opengraphImage = "/images/osprey.png"
  email = ""
  googleTagManager = ""
  customCSS = true

  # Social media links in footer
  twitter = "TomaNistor"
  linkedin = "tomanistor"
  github = "tomanistor"
  facebook = ""

  # Copyright and theme author credit in footer
  copyright = false
  credit = false

  # Cache busting of static resources (additional set up required)
  cacheBustCSS = true
  cacheBustJS = true

  # Code highlighting with highlight.js
  highlightJS = true
  highlightJSStyle = "" # For custom highlight.js styles, add your /path/to/styles/default.css
  highlightJSScript = "" # For custom highlight.js languages config, add your /path/to/highlight.pack.js

  # Choose either Formspree contact form or Basin contact form
  ajaxFormspree = false
  ajaxFormspreeGold = false
  ajaxBasin = "https://usebasin.com/f/0eae7044d4c2"

  # Lazy loading with lazysizes
  lazyloading = true

[[menu.main]]
  name = "About"
  url  = "/#about"
  weight = 1
  [menu.main.ka]
    ka = "ჩვენ შესახებ"

[[menu.main]]
  name = "Work"
  url  = "/#work"
  weight = 2
  [menu.main.i18n]
    ka = "საქმიანობა"

[[menu.main]]
  name = "Blog"
  url  = "/#blog"
  weight = 3
  [menu.main.i18n]
    ka = "ბლოგი"

[[menu.main]]
  name = "Contact"
  url  = "/#contact"
  weight = 4
  [menu.main.i18n]
    ka = "კონტაქტი"
